# fly.toml app configuration file generated for zerotha-backend-old-shape-9245 on 2024-02-18T17:33:15+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zerotha-backend-old-shape-9245'
primary_region = 'hkg'

[build]

[env]
  HOSTNAME = '0.0.0.0'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
