package com.zerodha.backend.enums;

public enum Sector {
    ENERGY,
    MATERIALS,
    INDUSTRIALS,
    UTILITIES,
    HEALTHCARE,
    FINANCIALS,
    CONSUMER_DISCRETIONARY,
    CONSUMER_STAPLES,
    INFORMATION_TECHNOLOGY,
    COMMUNICATION,
    REAL_ESTATE,
    ETF,
    INDEX_FUNDS
}
