# Common
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO

# Development
---
#spring:
#  config:
#    activate:
#      on-profile: "dev"
#  datasource:
#    url: jdbc:postgresql://localhost:5431/zerotha
#    username: postgres
#    password: root1234
#    driver-class-name: org.postgresql.Driver

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:postgresql://db.ngglxzbzmnvkqsaggtua.supabase.co:5432/postgres
    username: postgres
    password: GenkinLabs@5324

# Production
---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:postgresql://db.ngglxzbzmnvkqsaggtua.supabase.co:5432/postgres
    username: postgres
    password: GenkinLabs@5324