# Common
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO

# Development
---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:postgresql://localhost:5432/zerotha
    username: postgres
    password: GenkinLabs
    driver-class-name: org.postgresql.Driver

# Production
---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:postgresql://db.hzndyjtfxvikkjvuxbcp.supabase.co:5432/postgres
    username: postgres
    password: GenkinLabs@5324
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL