# Common
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO

# Development
---
#spring:
#  config:
#    activate:
#      on-profile: "dev"
#  datasource:
#    url: jdbc:postgresql://localhost:5431/zerotha
#    username: postgres
#    password: root1234
#    driver-class-name: org.postgresql.Driver

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:postgresql://dpg-cn8vcb2cn0vc738pg17g-a.oregon-postgres.render.com:5432/sample_245a?user=sample_245a_user&password=y8sn2wehTZ0tCLjMmdmzkwTxmbDAHIp8
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL

# Production
---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:postgresql://dpg-cn8vcb2cn0vc738pg17g-a.oregon-postgres.render.com:5432/sample_245a?user=sample_245a_user&password=y8sn2wehTZ0tCLjMmdmzkwTxmbDAHIp8
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL

# Production Supa
---
spring:
  config:
    activate:
      on-profile: "prod_supa"
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.ngglxzbzmnvkqsaggtua&password=GenkinLabs@5324
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL