# Common
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO

# Development
---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:postgresql://localhost:5431/zerotha
    username: postgres
    password: root1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL

# Production Supabase
---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: ${PROD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL